"""Initial migration

Revision ID: 7e53c73972cb
Revises: 
Create Date: 2023-02-08 20:40:12.753111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7e53c73972cb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('persons')
    tasks_table = op.create_table(
        "tasks",
        sa.Column("id", mysql.VARCHAR(length=50), primary_key=True),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=30), nullable=False),
        sa.Column("priority", mysql.VARCHAR(length=30), nullable=False),
        sa.Column("notes", mysql.VARCHAR(length=500), nullable=True),
        sa.Column("created_by", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("assigned_to", mysql.VARCHAR(length=50), nullable=True),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        tasks_table,
        [
            {
                "id": "62a46bd5-ac7d-4387-91f4-71435d81c962",
                "name": "Cook food",
                "status": "In progress",
                "priority": "Important",
                "notes": "Lorem ipsum",
                "created_by": "Bruce",
                "assigned_to": "Snowy",
            },
            {
                "id": "d0ab2879-4016-4659-a7e6-4953258eae92",
                "name": "Wash clothes",
                "status": "Not started",
                "priority": "Urgent",
                "notes": "Lorem ipsum",
                "created_by": "Bruce",
                "assigned_to": "Bruce",
            },
            {
                "id": "3601d971-cf17-424b-a086-4d8ecda5b313",
                "name": "Clean room",
                "status": "In progress",
                "priority": "Medium",
                "notes": "Lorem ipsum",
                "created_by": "Bruce",
                "assigned_to": "Papsy",
            },
            {
                "id": "38edca94-ccb1-449a-afd9-ccd3d6737b05",
                "name": "Sweep floor",
                "status": "In progress",
                "priority": "Low",
                "notes": "Lorem ipsum",
                "created_by": "Bruce",
                "assigned_to": "Papsy",
            },
            {
                "id": "2e318ea2-575a-49b2-ba71-32bbcd928146",
                "name": "Feed dogs",
                "status": "Not started",
                "priority": "Important",
                "notes": "Lorem ipsum",
                "created_by": "Bruce",
                "assigned_to": "Bruce",
            },
            {
                "id": "ef964799-bb9c-4f2b-8896-1beb97fcd693",
                "name": "Buy food",
                "status": "In progress",
                "priority": "Urgent",
                "notes": "Lorem ipsum",
                "created_by": "Bruce",
                "assigned_to": "Bruce",
            },
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
