"""Initial migration

Revision ID: 7e53c73972cb
Revises: 
Create Date: 2023-02-08 20:40:12.753111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7e53c73972cb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('persons')
    tasks_table = op.create_table(
        "tasks",
        sa.Column("id", mysql.VARCHAR(length=50), primary_key=True),
        sa.Column("name", mysql.VARCHAR(length=300), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=500), nullable=True),
        sa.Column("priority", mysql.INTEGER, nullable=False),
        sa.Column("author",  mysql.VARCHAR(length=50), nullable=False),
        sa.Column("due_date", mysql.DATETIME, nullable=True),
        sa.Column("created_at", mysql.DATETIME, nullable=False),
        sa.Column("updated_at", mysql.DATETIME, nullable=False),
        sa.Column("is_complete", mysql.BOOLEAN, nullable=False)
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        tasks_table,
        [
            {
                "id": "62a46bd5-ac7d-4387-91f4-71435d81c962",
                "name": "Cook food",
                "description": "Lorem ipsum",
                "priority": 2,
                "author": "40edeec4-8a93-4d19-bcf7-9241d23cccfb",
                "due_date": "2023-02-01 09:23:23",
                "created_at": "2023-01-28 09:23:23",
                "updated_at": "2023-01-29 09:23:23",
                "is_complete": 1
            },
            {
                "id": "3601d971-cf17-424b-a086-4d8ecda5b313",
                "name": "Clean room",
                "description": "Lorem ipsum",
                "priority": 1,
                "author": "91d2a774-a493-401a-9d00-c34f714db745",
                "due_date": "2023-02-04 09:23:23",
                "created_at": "2023-01-12 09:23:23",
                "updated_at": "2023-01-14 09:23:23",
                "is_complete": 0,
            },
            {
                "id": "38edca94-ccb1-449a-afd9-ccd3d6737b05",
                "name": "Sweep floor",
                "description": "Lorem ipsum",
                "priority": 3,
                "author": "40edeec4-8a93-4d19-bcf7-9241d23cccfb",
                "due_date": "2023-02-12 09:23:23",
                "created_at": "2023-01-01 09:23:23",
                "updated_at": "2023-01-04 09:23:23",
                "is_complete": 1,
            },
            {
                "id": "2e318ea2-575a-49b2-ba71-32bbcd928146",
                "name": "Feed dogs",
                "description": "Lorem ipsum",
                "priority": 2,
                "author": "40edeec4-8a93-4d19-bcf7-9241d23cccfb",
                "due_date": "2023-02-15 09:23:23",
                "created_at": "2023-01-21 09:23:23",
                "updated_at": "2023-01-23 09:23:23",
                "is_complete": 0,
            },
            {
                "id": "ef964799-bb9c-4f2b-8896-1beb97fcd693",
                "name": "Buy food",
                "description": "Lorem ipsum",
                "priority": 4,
                "author": "40edeec4-8a93-4d19-bcf7-9241d23cccfb",
                "due_date": "2023-02-12 09:23:23",
                "created_at": "2023-01-03 09:23:23",
                "updated_at": "2023-01-04 09:23:23",
                "is_complete": 1,
            },
            {
                "id": "d0ab2879-4016-4659-a7e6-4953258eae92",
                "name": "Wash clothes",
                "description": "Lorem ipsum",
                "priority": 1,
                "author": "40edeec4-8a93-4d19-bcf7-9241d23cccfb",
                "due_date": "2023-02-08 09:23:23",
                "created_at": "2023-01-20 09:23:23",
                "updated_at": "2023-01-21 09:23:23",
                "is_complete": 1,
            },
        ],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
